# -*- coding: utf-8 -*-
"""Projeto - Estoque Floricultura

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lpnqip7bhiN9-vwip9ZjsqDlO9jGi2wb
"""

estoque = {
    'Muda de Rosa': [50, 15.00, 'Plantas ornamentais de cores variadas.'],
    'Árvore Frutífera': [30, 25.00, 'Planta que produz frutos após alguns anos.'],
    'Cacto': [20, 10.00, 'Planta de baixa manutenção, ideal para ambientes secos.'],
    'Bromélia': [10, 20.00, 'Planta tropical que adora ambientes úmidos.'],
    'Orquídea': [15, 40.00, 'Planta delicada e de flores coloridas.']
}

lista_de_compras = []

#Exibindo o estoque
def exibir_estoque():
    print("\nEstoque Disponível:")
    for i, (item, dados) in enumerate(estoque.items(), 1):
        print(f"{i}. {item} - {dados[2]} - Preço: R${dados[1]:.2f} por unidade - {dados[0]} unidades disponíveis")

#Buscar item por nome ou descrição
def buscar_item(termo):
    encontrados = []
    for item, dados in estoque.items():
        if termo.lower() in item.lower() or termo.lower() in dados[2].lower():
            encontrados.append((item, dados))

    if encontrados:
        print("\nResultados da Busca:")
        for item, dados in encontrados:
            print(f"{item} - {dados[2]} - Preço: R${dados[1]:.2f} por unidade - {dados[0]} unidades disponíveis")
    else:
        print("\nNenhum item encontrado para o termo:", termo)

#Add um item na lista de compras
def adicionar_à_lista(indice, quantidade):
    #Verifica se o índice é válido
    if 1 <= indice <= len(estoque):
        item_nome = list(estoque.keys())[indice - 1]
        #Verifica se tem estoque suficiente
        if estoque[item_nome][0] >= quantidade:
            #Atualiza o estoque
            estoque[item_nome][0] -= quantidade
            #Adiciona o item na lista de compras
            lista_de_compras.append((item_nome, quantidade, estoque[item_nome][1]))  #(nome, quantidade, preço)
            print(f"\n{quantidade} unidade(s) de '{item_nome}' adicionada(s) à lista de compras.")
        else:
            print("\nEstoque insuficiente!")
    else:
        print("\nSeleção inválida, por favor escolha um item válido!")

#Função para exibir a lista de compras e calcular o valor total
def exibir_lista_compras():

    if lista_de_compras:
        total = 0
        print("\nLista de Compras:")
        for item, quantidade, preco in lista_de_compras:
            total += quantidade * preco
            print(f"{item} - {quantidade} unidade(s) - Preço: R${preco:.2f} cada")
        print(f"\nValor Total da Compra: R${total:.2f}")
    else:
        print("\nSua lista de compras está vazia!")

#Função para operar sobre o estoque e a lista de compras
def operar_estoque():
    while True:
        print("\nMenu de Opções:")
        print("0. Sair")
        print("1. Exibir Estoque")
        print("2. Buscar Plantas")
        print("3. Adicionar Item à Lista de Compras")
        print("4. Exibir Lista de Compras")

        #Opções do menu
        opcao = int(input("Escolha a opção desejada (número): "))

        if opcao == 0:
            print("Saindo do sistema...")
            break
        elif opcao == 1:
            exibir_estoque()
        elif opcao == 2:
            termo = input("Digite o termo de busca (nome da planta): ")
            buscar_item(termo)
        elif opcao == 3:
            #Exibe o estoque numerado
            exibir_estoque()
            try:
                indice = int(input("Escolha o número do item a ser adicionado à lista de compras: "))
                quantidade = int(input("Digite a quantidade desejada: "))
                adicionar_à_lista(indice, quantidade)  #Adiciona na lista de compras
            except ValueError:
                print("\nPor favor, insira um número válido.")
        elif opcao == 4:
            exibir_lista_compras()  #Mostra a lista de compras
        else:
            print("Opção inválida. Tente novamente.")

#Função principal
def main():
    operar_estoque()

# Para rodar o sistema
if __name__ == "__main__":
    main()